name: Create Frontend Sync Issue

on:
  push:
    branches: [ main ]
    paths:
      - 'protocols.json'

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get protocols info
      id: info
      run: |
        PROTOCOLS_COUNT=$(jq '.protocols | length' protocols.json)
        LAST_UPDATED=$(jq -r '.lastUpdated' protocols.json)
        echo "count=$PROTOCOLS_COUNT" >> $GITHUB_OUTPUT
        echo "updated=$LAST_UPDATED" >> $GITHUB_OUTPUT

    - name: Create issue in frontend repo
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const frontendRepo = 'operators-frontend';

          const issueBody = `## 🔄 protocols.json Updated

          The operators data has been updated and needs to be synced to the frontend.

          **Changes:**
          - **Protocols count:** ${{ steps.info.outputs.count }}
          - **Last updated:** ${{ steps.info.outputs.updated }}
          - **Commit:** [\`${{ github.sha }}\`](https://github.com/${owner}/operators/commit/${{ github.sha }})

          **Action needed:**
          Please sync the changes by running:
          \`\`\`bash
          cd operators-frontend
          cp ../operators/protocols.json public/protocols.json
          git add public/protocols.json
          git commit -m "sync: update protocols.json from operators@${{ github.sha }}"
          git push
          \`\`\`

          **Or using the direct copy:**
          \`\`\`bash
          curl -o public/protocols.json https://raw.githubusercontent.com/${owner}/operators/main/protocols.json
          \`\`\`

          This issue will auto-close when the sync is complete.`;

          await github.rest.issues.create({
            owner: owner,
            repo: repo,
            title: '🔄 Sync needed: protocols.json updated',
            body: issueBody,
            labels: ['sync', 'automated']
          });